config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  
  resources :applicants do
    member do
      get :change
    end
  end
  resources :accountabilities
  resources :announcements
  get 'administrator/admin' #ano ine?

  resources :permissions do
    member do
      get :change
    end
  end
  get 'sessions/new'

  
  
  get '/', to: 'pages#home'
  get 'users/:id/accountability', to: 'users#user_accountability'
  get 'users/:id/violations', to: 'users#userViolations'
  get 'users/:id/submittedPermits', to: 'users#submittedPermits'
  
  get '/rules' => 'rules#show'
  get '/rules/download' => 'rules#download'
  
  get '/home' => 'pages#home'
  get '/admin' => 'administrator#admin'
  get '/announcements' => 'announcements#index'
  get '/contact', to: 'pages#contact'
  get '/about', to: 'pages#about'
  get '/help', to: 'pages#help'
  get '/contact', to: 'static_pages#contact'
  get '/signup',  to: 'users#new'
  get '/login',   to: 'sessions#new'
  get '/apply', to: 'applicants#new'
  post '/login',   to: 'sessions#create'
  put '/permissions', to: 'permissions#permissionStatus'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  
 
  
  

end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_many :accountabilities
  has_many :permissions
  
  attr_accessor :remember_token, :activation_token
  before_save   :downcase_email
  before_create :create_activation_digest
    
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true


  # def user
  #   scope :alphabetically, order("name ASC")
  # end
  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  # Returns the hash digest of the given string.
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def self.new_token
    SecureRandom.urlsafe_base64
  end
  
  # Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end
  
  class << self
    # Returns the hash digest of the given string.
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    # Returns a random token.
    def new_token
      SecureRandom.urlsafe_base64
    end
  end
  
  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  
  
  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  # Activates an account.
  def activate
    update_columns(activated: FILL_IN, activated_at: FILL_IN)
  end

  # Sends activation email.
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
    # user.activate!
  end
  
  private

    # Converts email to all lower-case.
    def downcase_email
      self.email = email.downcase
    end

    # Creates and assigns the activation token and digest.
    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def index
    # @users = User.where(activated: FILL_IN).paginate(page: params[:page])
    @users = User.all.paginate(page: params[:page], per_page: 5)
  end

  def show
    @user = User.find(params[:id])
    #@user = User.alphabetically
    @accountabilities = Accountability.where(user_id:params[:id].to_i)
    @permissions = Permission.where(user_id:[@user.id.to_i])
    # redirect_to root_url and return unless FILL_IN
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.age = Date.today.year - @user.birthday.year
    if @user.save
      ApplicantMailer.sample_email(@user).deliver_now
      flash[:info] = "Account created! An Email has been sent to the applicant"
      redirect_to applicants_url
    else
      render 'new'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end
  
  def edit
  end
  
  def update
    if @user.update_attributes(user_params)
      @user.age = Date.today.year - @user.birthday.year
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def user_accountability
    @accountabilities = Accountability.where(user_id:params[:id].to_i)
    @user = User.find(params[:id])
   
    render "accountability"
  end
  
  def userViolations
    @accountabilities = Accountability.where(user_id:params[:id].to_i)
    @user = User.find(params[:id])
    
    render "violations"
  end
  
  def submittedPermits
    @user = User.find(params[:id])
    @permissions = Permission.where(user_id:[@user.id.to_i])
    render "submitted_permits"
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation, :student_number, :course_and_year,
                                   :sts_bracket, :family_name, :middle_name, :home_address,
                                  :contact_number, :birthday)
    end
    
    # Before filters

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
    
    # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_accountOverview.html.erb
<% if !current_user.admin? %>
<div class="col-md-3">
      <%= render 'user_sidebar' %>
</div>
<% end %>
<div class="col-md-9">
     <!-- SIDEBAR USERPIC -->
     <!--<div class="profile-userpic col-sm-12" >-->
     <!--  %= gravatar_for @user %-->
     <!--</div>-->
     <!-- END SIDEBAR USERPIC -->
     <!-- SIDEBAR USER TITLE -->
     <!--<div class="profile-usertitle">-->
     <!--	<div class="profile-usertitle-name">-->
               <!--%= @user.name %		-->
     <!--	</div>-->
     <!--	<div class="profile-usertitle-job">-->
     <!--		Student number here-->
     <!--	</div>-->
     <!--</div>-->
     <!-- END SIDEBAR USER TITLE -->
     <div class="row">
          <div>
               <h3>Personal Information</h3>
               <% if current_user.admin? && !current_user?(@user) %>
                    <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#info">details</button>
               <% end %>
          </div>
          <hr/>
          <div id="info" class= "<%= current_user.admin? === true ? 'collapse':''%>">
               <div class="col-sm-3"><h4>Name: </h4></div>
               <div class="col-sm-9"><h4><%= @user.family_name %>, <%= @user.name %> <%= @user.middle_name %></h4></div>
               <div class="col-sm-3"><h4>Student Number: </h4></div>
               <div class="col-sm-9"><h4><%= @user.student_number %></h4></div>
               <div class="col-sm-3"><h4>Course & Year: </h4></div>
               <div class="col-sm-9"><h4><%= @user.course_and_year %></h4></div>
               <div class="col-sm-3"><h4>Contact Number: </h4></div>
               <div class="col-sm-9"><h4><%= @user.contact_number %></h4></div>
               <div class="col-sm-3"><h4>Email Address: </h4></div>
               <div class="col-sm-9"><h4><%= @user.email %></h4></div>
          </div>
     </div>
     <div class="row">
          <div>
               <h3>Additional Information</h3>
               <% if current_user.admin? && !current_user?(@user) %>
                    <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#info2">details</button>
               <% end %>
          </div>
          <hr/>
          <div id="info2" class="<%= current_user.admin? === true ? 'collapse':''%>">
               <div class="col-sm-3"><h4>STS Bracket: </h4></div>
               <div class="col-sm-9"><h4><%= @user.sts_bracket %></h4></div>
               <div class="col-sm-3"><h4>Birthday: </h4></div>
               <div class="col-sm-4"><h4><%= @user.birthday %></h4></div>
               <div class="col-sm-2"><h4>Age: </h4></div>
               <div class="col-sm-3"><h4><%= @user.age %></h4></div>
               <div class="col-sm-3"><h4>Home Address: </h4></div>
               <div class="col-sm-9"><h4><%= @user.home_address %></h4></div>
          </div>
     </div>
     <div class="row">
          <div>
               <h3>Contact Persons</h3>
               <% if current_user.admin? && !current_user?(@user) %>
                    <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#info3">details</button>
               <% end %>
          </div>
          <hr/>
          <div id="info3" class="<%= current_user.admin? === true ? 'collapse':''%>">
               
          </div>
     </div>
</div>

app/views/users/_adminLoginPage.html.erb
<h1>Manage Dormer Information</h1>
<div class="row">
     <div class="col-sm-3">
          <h4>Manage Users</h4>
     </div>
     
     <div class="col-sm-3">
          <h4>Manage Permits</h4>
     </div>
     
     <div class="col-sm-3">
          <h4>Manage Accountabilities</h4>
     </div>
     
     <div class="col-sm-3">
          <h4>Manage Announcements</h4>
     </div>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: @user %>
  <%= params[:param0] %>

  <h3>Primary Information</h3>
  <%= f.label :name %>
  <%= f.text_field :name, :value => params[:param1], class: 'form-control' %>
  
  <%= f.label :family_name %>
  <%= f.text_field :family_name, :value => params[:param2], class: 'form-control' %>
  
   <%= f.label :middle_name %>
  <%= f.text_field :middle_name, class: 'form-control' %>
  
  <%= f.label :student_number %>
  <%= f.text_field :student_number, :value => params[:param3], class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, :value => params[:param4], class: 'form-control'%>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>
  
  </br></br><hr/>
  <h3>Additional Information</h3></br>
  
  <%= f.label :course_and_year %>
  <%= f.text_field :course_and_year, class: 'form-control' %></br>
  
  <%= f.label 'STS Bracket' %></br>
  <%= f.select :sts_bracket, ['ND','PD40','PD60','PD80','FD', 'FDS'], class: 'form-control' %></br></br>
  
  <%= f.label :home_address %>
  <%= f.text_field :home_address, class: 'form-control' %>
  
  </br>
  <%= f.label :birthday %></br>
  <%= f.date_select :birthday, :start_year => 1900, class:'form-control' %>
  </br></br>
  
  <%= f.label :contact_number %>
  <%= f.text_field :contact_number, class: 'form-control' %>
  
  <%= f.hidden_field :applicant_id, :value => params[:param0] %>

  </br></br>
  <%= f.button :submit, name: 'subaction', value: 'update', class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
      | <%= link_to "Delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
    | <%= link_to "Add Accountability", new_accountability_path(:user_id => user.id) %>
  <% end %>
</li>

app/views/users/_user_sidebar.html.erb
<div class="profile-sidebar">
     
     <!-- SIDEBAR MENU -->
     <div class="profile-usermenu">
     	<ul class="nav">
     		<li class="<%= 'active' if current_page?(current_user) %>">
     			<%= link_to current_user do %>
            			<i class="glyphicon glyphicon-user"></i>
            			Account Overview
                    <% end %>
     		</li>
     		<li class="<%= 'active' if current_page?(url_for(current_user) + '/accountability')%>">
     			<%= link_to url_for(current_user) + '/accountability' do %>
            			<i class="glyphicon glyphicon-usd"></i>
            			Accountabilities
                    <% end %>
     		</li>
     	     <li class="<%= 'active' if current_page?(url_for(current_user) + '/violations')%>">
     			<%= link_to url_for(current_user) +'/violations' do %>
            			<i class="glyphicon glyphicon-ban-circle"></i>
            			Violations
                    <% end %>
     		</li>
     		<li class="<%= 'active' if current_page?(url_for(current_user) + '/submittedPermits')%>">
     			<%= link_to url_for(current_user) +'/submittedPermits' do %>
            			<i class="glyphicon glyphicon-thumbs-up"></i>
            			Submitted Permits
                    <% end %>
     		</li>
     		<li>
     			<%= link_to new_permission_path(:user_id => current_user.id) do %>
            			<i class="glyphicon glyphicon-list-alt"></i>
            			Apply for Permit
                    <% end %>
     		</li>
     	</ul>
     </div>
     <!-- END MENU -->
</div>

app/views/users/accountability.html.erb
<div class="col-md-3">
      <%= render 'user_sidebar' %>
</div>

<div class="col-md-9">
     <h1>
          Accountabilties
     </h1>
     <p id="notice"><%= notice %></p>

    <% if @accountabilities.empty? || @accountabilities.where(classification:['Payment']).count == 0%>
      <pre style="font-size:18px; text-align:justify">
        No existing accountabilities
      </pre>
    <% else %>
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>Classification</th>
            <th>Description</th>
            <th>Due date</th>
            <th>Payment</th>
          </tr>
        </thead>
      
        <tbody>
          <% @accountabilities.each do |accountability| %>
            <% if accountability.classification == "Payment" then %>
              <tr>
                <td><%= accountability.classification %></td>
                <td><%= accountability.description %></td>
                <td><%= accountability.due_date%></td>
                <td><%= accountability.payment %></td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    <% end %>
</div>

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<% provide(:button_text, 'Save changes') %>
<h1>Update your profile</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">Change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<!--ini kanan admin la ini-->

<% provide(:title, 'All users') %>
<h1>All users</h1>
<!--<%= will_paginate %>-->
<ul class="users">
  <%= render @users %>
</ul>
<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create account') %>
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/payments.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <div class="col-md-3">
	<%= render 'user_sidebar' %>
  </div>
  
  <div class="col-md-9">
    <h1>
          Payments Details here
    </h1>
  </div>
</div>

app/views/users/show.html.erb
  <% provide(:title, @user.name) %>
  <div class="row">
    <% if @user.admin then %>
      <%= render "adminLoginPage"  %>
    <% else %>
      <%= render partial: "accountOverview", locals: {user: @user} %>
  	<% end %>
    
    <% if current_user.admin? && !current_user?(@user) %>
      <div class="col-md-9">
      
       <h3> Accountabilties </h3>
       <hr/>
       <p id="notice"><%= notice %></p>
  
        <table class="table table-striped table-hover">
          <thead>
            <tr>
            <th>Classification</th>
            <th>Description</th>
            <th>Payment</th>
          </tr>
          </thead>
  
          <tbody>
            <% @accountabilities.each do |accountability| %>
            <tr>
              <td><%= accountability.classification %></td>
              <td><%= accountability.description %></td>
              <td><%= accountability.payment %></td>
            </tr>
            <% end %>
            </tbody>
        </table>
      </div>
      
      <div class="col-md-9">
      
       <h3> Submitted Permits </h3>
       <hr/>
       <p id="notice"><%= notice %></p>
  
        <table class="table table-striped table-hover">
          <thead>
            <tr>
             
             <th>Permit type</th>
             <th>Description</th>
             <th>Status</th>
             <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
           <% @permissions.each do |permission| %>
              <tr>
               
                <td><%= permission.permit_type %></td>
                <td><%= permission.description %></td>
                <td class="<%= permission.approved ?  'btn-sm btn-success': 'btn-sm btn-danger' %>"> <%= permission.approved ? 'approved' : 'not approved' %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    <% end %>
  </div>
  
  

app/views/users/submitted_permits.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <div class="col-md-3">
	<%= render 'user_sidebar' %>
  </div>
  
  <div class="col-md-9">
    <h1 style="text-align: center">Submitted Permits</h1>
      <% if @permissions.empty? %>
        <pre style="font-size:18px; text-align:justify">
          You have not submitted any permits yet
        </pre>
      <% else %>
        <table class="table table-striped table-hover">
          <thead>
            <tr>
             
             <th>Permit type</th>
             <th>Permit Date</th>
             <th>Description</th>
             <th>Status</th>
             <th colspan="3"></th>
            </tr>
          </thead>
  
          <tbody>
           <% @permissions.each do |permission| %>
              <tr>
               
                <td><%= permission.permit_type %></td>
                <td><%= permission.permit_date %></td>
                <td><%= permission.description %></td>
                <td class="<%= permission.approved ?  'btn-sm btn-success': 'btn-sm btn-danger' %>"> <%= permission.approved ? 'approved' : 'not approved' %></td>
              </tr>
            <% end %>
          </tbody>
      </table>
    <% end %>

    <br>
  </div>
</div>

app/views/users/violations.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <div class="col-md-3">
	<%= render 'user_sidebar' %>
  </div>
  
  <div class="col-md-9">
    <h1>Violations</h1>
    <% if @accountabilities.empty? || @accountabilities.where(classification:['Violation']).count == 0%>
      <pre style="font-size:18px; text-align:justify">
        You have not violated anything
      </pre>
    <% else %>
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>Classification</th>
            <th>Description</th>
            <th>Remarks</th>
          </tr>
        </thead>
  
        <tbody>
          <% @accountabilities.each do |accountability| %>
            <% if accountability.classification == "Violation" then %>
              <tr>
                <td><%= accountability.classification %></td>
                <td><%= accountability.description %></td>
                <td><%= accountability.remarks %></td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>