config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  
  resources :applicants do
    member do
      get :change
    end
  end
  resources :accountabilities
  resources :announcements
  get 'administrator/admin' #ano ine?

  resources :permissions do
    member do
      get :change
    end
  end
  get 'sessions/new'

  
  
  get '/', to: 'pages#home'
  get 'users/:id/accountability', to: 'users#user_accountability'
  get 'users/:id/violations', to: 'users#userViolations'
  get 'users/:id/submittedPermits', to: 'users#submittedPermits'
  
  get '/rules' => 'rules#show'
  get '/rules/download' => 'rules#download'
  
  get '/home' => 'pages#home'
  get '/admin' => 'administrator#admin'
  get '/announcements' => 'announcements#index'
  get '/contact', to: 'pages#contact'
  get '/about', to: 'pages#about'
  get '/help', to: 'pages#help'
  get '/contact', to: 'static_pages#contact'
  get '/signup',  to: 'users#new'
  get '/login',   to: 'sessions#new'
  get '/apply', to: 'applicants#new'
  post '/login',   to: 'sessions#create'
  put '/permissions', to: 'permissions#permissionStatus'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  
 
  
  

end

app/models/accountability.rb
class Accountability < ActiveRecord::Base
     belongs_to :users
end

app/controllers/accountabilities_controller.rb
class AccountabilitiesController < ApplicationController
  before_action :set_accountability, only: [:show, :edit, :update, :destroy]

  # GET /accountabilities
  # GET /accountabilities.json
  def index
    @user = User.all
    @accountabilities = Accountability.all
  end

  # GET /accountabilities/1
  # GET /accountabilities/1.json
  def show
  end

  # GET /accountabilities/new
  def new
    @accountability = Accountability.new
    @accountability.user_id = params[:user_id].to_i
  end

  # GET /accountabilities/1/edit
  def edit
  end

  # POST /accountabilities
  # POST /accountabilities.json
  def create
    @accountability = Accountability.new(accountability_params)
    
    respond_to do |format|
      if @accountability.save
        format.html { redirect_to users_path, notice: 'Accountability was successfully created.' }
        format.json { render :show, status: :created, location: @accountability }
      else
        format.html { render :new }
        format.json { render json: @accountability.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accountabilities/1
  # PATCH/PUT /accountabilities/1.json
  def update
    respond_to do |format|
      if @accountability.update(accountability_params)
        format.html { redirect_to @accountability, notice: 'Accountability was successfully updated.' }
        format.json { render :show, status: :ok, location: @accountability }
      else
        format.html { render :edit }
        format.json { render json: @accountability.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accountabilities/1
  # DELETE /accountabilities/1.json
  def destroy
    @accountability.destroy
    respond_to do |format|
      format.html { redirect_to accountabilities_url, notice: 'Accountability was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_accountability
      @accountability = Accountability.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def accountability_params
      params.require(:accountability).permit(:classification, :description, :payment, :user_id, :remarks, :due_date)
    end
end

app/helpers/accountabilities_helper.rb
module AccountabilitiesHelper
end

app/views/accountabilities/_form.html.erb
<%= form_for(@accountability) do |f| %>
  <% if @accountability.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@accountability.errors.count, "error") %> prohibited this accountability from being saved:</h2>

      <ul>
      <% @accountability.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :classification %><br>
    <%= f.select :classification , ['Payment', 'Violation']%>
  </div>
  
   <div class="field">
    <%= f.label :due_date %></br>
    <%= f.date_select :due_date, :start_year => Date.today.year, class:'form-control' %>
  </div>
  
  <div class="field">
    <%= f.label :remarks%><br>
    <%= f.text_area :remarks %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :payment %><br>
    <%= f.number_field :payment %>
  </div>
  
  <%= f.hidden_field :user_id, :value => @accountability.user_id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accountabilities/edit.html.erb
<h1>Editing Accountability</h1>

<%= render 'form' %>

<%= link_to 'Show', @accountability %> |
<%= link_to 'Back', accountabilities_path %>

app/views/accountabilities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Accountabilities</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>User</th>
      <th>Classification</th>
      <th>Description</th>
      <th>Payment</th>
      <th>Due date</th>
      <th>Action</th>
      <th colspan="3">
    </tr>
  </thead>

  <tbody>
    <% @accountabilities.each do |accountability| %>
      <tr>
        <td><%= @user.find(accountability.user_id).name %></td>
        <td><%= accountability.classification %></td>
        <td><%= accountability.description %></td>
        <td><%= accountability.payment %></td>
        <td><%= accountability.due_date %></td>
        <td><%= link_to 'Delete', accountability, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '', new_accountability_path %>

app/views/accountabilities/new.html.erb
<h1>New Accountability</h1>

<%= render 'form' %>

<%= link_to 'Back', accountabilities_path %>

app/views/accountabilities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Classification:</strong>
  <%= @accountability.classification %>
</p>

<p>
  <strong>Description:</strong>
  <%= @accountability.description %>
</p>

<p>
  <strong>Payment:</strong>
  <%= @accountability.payment %>
</p>

<p>
  <strong>User:</strong>
  <%= @accountability.user_id %>
</p>

<%= link_to 'Edit', edit_accountability_path(@accountability) %> |
<%= link_to 'Back', accountabilities_path %>