config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  
  resources :applicants do
    member do
      get :change
    end
  end
  resources :accountabilities
  resources :announcements
  get 'administrator/admin' #ano ine?

  resources :permissions do
    member do
      get :change
    end
  end
  get 'sessions/new'

  
  
  get '/', to: 'pages#home'
  get 'users/:id/accountability', to: 'users#user_accountability'
  get 'users/:id/violations', to: 'users#userViolations'
  get 'users/:id/submittedPermits', to: 'users#submittedPermits'
  
  get '/rules' => 'rules#show'
  get '/rules/download' => 'rules#download'
  
  get '/home' => 'pages#home'
  get '/admin' => 'administrator#admin'
  get '/announcements' => 'announcements#index'
  get '/contact', to: 'pages#contact'
  get '/about', to: 'pages#about'
  get '/help', to: 'pages#help'
  get '/contact', to: 'static_pages#contact'
  get '/signup',  to: 'users#new'
  get '/login',   to: 'sessions#new'
  get '/apply', to: 'applicants#new'
  post '/login',   to: 'sessions#create'
  put '/permissions', to: 'permissions#permissionStatus'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  
 
  
  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    For any inquiries, you may visit us at the University of the Philippines Visayas Tacloban College
  </small>
  <nav>
    <ul>
      <li>[TEL NO]</li>
      <li>[E ADDRESS]</li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "DDMS", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li id="home"><%= link_to "Home", root_path %></li>
        <!--<li> link_to "Help", help_path </li>-->
        <% if logged_in? %>
          <% if current_user && current_user.admin? %>
            <script> document.getElementById("home").remove() </script>
            <li><%= link_to "Users", users_path %></li>
            <li><%= link_to "Permits", permissions_path %></li>
            <li><%= link_to "Accountabilities", accountabilities_path %></li>
            <li><%= link_to "Announcements", announcements_path %></li>
            <li><%= link_to "Applicants", applicants_path %></li>
          <% else %>
            <li><%= link_to "Profile", current_user %></li>
          <% end %>
          <li><%= link_to "Rules", '/rules' %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <% if current_user && !current_user.admin? %>
                  <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <% else %>
                  <li><%= link_to "Profile", current_user %></li>
                <% end %>
                <li class="divider"></li>
                <li>
                  <%= link_to "Log out", logout_path, method: "delete" %>
                </li>
              </ul>
            </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
 <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= render 'layouts/rails_default' %>
  <%= render 'layouts/shim' %>
  <%= csrf_meta_tags %>
  <style>
    @import url('https://fonts.googleapis.com/css?family=Roboto+Slab');
    @import url('https://fonts.googleapis.com/css?family=Arimo');
  </style>
</head>
<body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <!--<%= render 'layouts/footer' %>-->
    </div>
</body>
</html>